### ISSUE TITLE
MoZBX on Zabbix 1.9 (or 2.0 RC's) login fails

### ISSUE THREAD

**Issue by mattiasgeniar** [mattiasgeniar/MoZBX#26]
Logins seem to fail on the new Zabbix 1.9 versions, including the 2.0 release candidates.

To check what the changes in the API may have been and correct where needed.

**Comment by zabcow** [comment]
is there any chance to get a patch for above issue? I'm using Zabbix 2.0.0rc1

my following check on the server:

curl -i -X POST -H 'Content-Type: application/json' -d '{"method": "user.authenticate", "id":1, "params": {"user": "Tester", "password": "check"}, "jsonrpc": "2.0"}' https://www.server.de/zabbix/api_jsonrpc.php

produce imho a correct answer:

HTTP/1.1 200 OK
Date: Sun, 18 Mar 2012 10:00:37 GMT
Server: Apache/2.2.22
X-Powered-By: PHP/5.3.3-7+squeeze3
Transfer-Encoding: chunked
Content-Type: application/json

{"jsonrpc":"2.0","result":"704a9fdd2509bcb653c3288493df1f1b","id":1}

but via MoZBX I got "Not authorized".

I have no better information, that the only change to API since Zabbix 1.9 is, all users have per default API access.

**Comment by zabcow** [comment]
ok, login problem is now fixed for me. I changed line 68 in class_zabbix.php

(old)        private $auth_token = false;
(new)      private $auth_token = "";

but now, I got errors in hostgroup like:

Notice: Undefined property: stdClass::$name in class_zabbix.php on line 211
Notice: Undefined property: stdClass::$internal in class_zabbix.php on line 212
Notice: Undefined property: stdClass::$dns in class_zabbix.php on line 259
Notice: Undefined property: stdClass::$ip in class_zabbix.php on line 260
Notice: Undefined property: stdClass::$useip in class_zabbix.php on line 261

**Comment by mattiasgeniar** [comment]
Good catch, the API now indeed requires the 'null' value instead of False. Changed it. It's compatible with 1.8.x installs as well.

The hostgroup listing is now also fixed.

**Comment by zabcow** [comment]
Hi Mattias,

thanks for responding on my request.

I still have problems using MoZBX with Zabbix 2.0.0rc3.

There are still messages on my iPhone screen like
Notice: Undefined property: stdClass::$dns (or $ip, $useip)
in class_zabbix.php lines 259 til 261

Between them, there are links to my host groups and when I
follow them up, I got only a black screen and have to restart
the app link to start again over.

Sorry to tell you this.

Possible I can suppress the notice via php.ini, but I think
this is not the correct way and also it won't fix the black
screen.
Unfortunately my knowledge with html and java scripting is
not so good to fixit ;-)

With regards

Gerhard Kugland

Am 05.05.2012 14:13, schrieb Mattias Geniar:

**Comment by mattiasgeniar** [comment]
Hi,

Thanks for the report, the DNS/IP listing per host is one of the big changes in Zabbix 2.0 (with multiple values for each host) and it seems the API is not (yet) returning values for that.

I've modified MoZBX for now to do some proper error handling if those values are missing, but it also means the values won't yet be present.

Will add that as a todo.

**Comment by zabcow** [comment]
Hi Matthias,

ok, that fixed the problem with the notifications
and also correct number of hosts are printed out.

Waiting for good news referring to API 1.4 of
Zabbix 2.0  ;-)

-Gerhard

Am 05.05.2012 16:11, schrieb Mattias Geniar:
